Feat: Block Container 공통 기능 구현
Loadify/testy95-client pull request #7
Opened 2024-08-14 14:02 UTC by noeyigg

## 제목

Block Container 공통 기능 구현

## 내용

Block Container에 있는 블록을 drag하면 빨간색 테두리로 표시되고, Dashboard에 drop하면 순서대로 블록이 생성됩니다.

## 항목

- Block Container의 블록 drag & drop
- Block Dashboard에 순서대로 블록 생성
- 블록 drag시 빨간색 테두리 표시

## 특이 사항

- 칸반 명세에 따라 drop된 위치를 통해 해당 라인블록 위에 렌더링 되는 기능은 구현하지 않았습니다.
- 마찬가지로 Input Block의 input창에 사용자가 입력한 value가 유지되지 않습니다. (placeholder는 유지됩니다.)
- dashboard 영역에 drop되면 1번 라인블록 위에 drop된 블록이 생성됩니다.
- <LineBlockContainer> 스타일 컴포넌트가 li인데, 내부에서 map으로 li로 block을 생성해 오류가 발생합니다.

## 주의 사항

- [x] PR 크기는 300~500줄로 하되 최대 1000줄 미만으로 합니다.
- [x] conflict를 모두 해결하고 PR을 올려주세요

# PR 전 체크리스트

- [x] 가장 최신 브랜치를 pull 하였습니다
- [x] base 브랜치명을 확인하였습니다
- [x] 코드 컨벤션을 모두 확인하였습니다
- [x] 셀프 리뷰를 진행하였습니다.
- [x] 브랜치명을 확인하였습니다.
- [x] 작업 중 dependency 변경사항이 있는 경우 안내해주세요!

2024-08-14 14:23 UTC, whoisrey requested changes
어려운 기능이였을텐데 순조롭게 기능 구현에 성공하신 기연님! 수고하셨습니다~

2024-08-14 14:23 UTC, whoisrey commented on src/components/BlockContainer.jsx
> +const BlockContainer = ({ onDragStart }) => {
혹시 onDragStart 이벤트를 다루는 함수를 props로 받는다면 `handleDragStart` 와 같은 이름으로 props를 받는 건 어떨까요?
만약 바꾼다면 아래 InputBlock에서 `onDragStart={() => onDragStart...}` 와 같은 코드의 중복을 피할 수 있을 것 같습니다!

2024-08-14 14:23 UTC, whoisrey commented on src/components/BlockDashboard.jsx
> +    <Section onDragOver={(e) => e.preventDefault()} onDrop={onDrop}>
혹시 컴포넌트에 함수를 작성한다면 아래와 같이 따로 선언한 함수를 넣는 건 어떨까요?
```jsx
const handleDragOver = (event) => {
  event.preventDefault();
};
```
관련 글 첨부합니다!
(추가로 약어도 지양하면 좋을 것 같다고 생각합니다!)

[참고 자료](https://medium.com/steady-study/%EB%B2%88%EC%97%AD-react-%EC%9D%B8%EB%9D%BC%EC%9D%B8-%ED%95%A8%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EC%84%B1%EB%8A%A5-9aef85552f2b)

2024-08-14 14:23 UTC, whoisrey commented on src/components/common/InputBlock.jsx
> +    <InputBlockContainer draggable="true" onDragStart={onDragStart}>
`draggable` 속성을 찾다보면 기본값이 `auto` 라고 나오는데 혹시 "true"로 명시해주신 이유가 있을까요?
[참고 자료](https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/draggable)

2024-08-14 14:23 UTC, whoisrey commented on src/components/common/LineBlock.jsx
> +    </LineBlockContainer>
현재는 block의 타입이 두 가지로 정해졌지만
- 다른 타입의 블록이 생길 경우,
- 블록의 타입이 없는 경우,

를 대처하기 위해 아래 switch 문을 작성하는 건 어떨까요?

```jsx
{blocks.map((block) => {
  switch (block.type) {
    case "input":
      return <InputBlock key={block.id} parameter={block.parameter} />;
    case "method":
      return <MethodBlock key={block.id} method={block.method} />;
    default:
      return <div key={block.id}>Unsupported block type</div>;
  }
})}
```

2024-08-14 14:23 UTC, whoisrey commented on src/pages/Main.jsx
> +  };
혹시 두 state를 하나의 객체에서 관리하는 건 어떨까요~?
```jsx
const Dashboard = () => {
  const [dashboardState, setDashboardState] = useState({
    blocks: [],
    draggedBlock: null
  });

  const handleDragStart = (block) => {
    setDashboardState(prevState => ({
      ...prevState,
      draggedBlock: block
    }));
  };

  const handleDrop = () => {
    const { draggedBlock } = dashboardState;
    if (draggedBlock) {
      setDashboardState(prevState => ({
        ...prevState,
        blocks: [...prevState.blocks, { ...draggedBlock, id: Date.now() }],
        draggedBlock: null
      }));
    }
  };
  ```

2024-08-14 15:14 UTC, choiOV approved these changes
양래님께서 인라인 함수, 코드의 확장성 등에 대한 양질의 리뷰를 남겨주신 덕분에 저도 많이 배우게 되었습니다! 그리고 기연님! 라이브러리 없이 드래그 앤 드랍 기능을 구현하기 까다로우셨을텐데 멋지게 구현해주셔서 감사합니다! 두 분 모두 오늘도 수고 많으셨습니다!

2024-08-14 16:45 UTC, noeyigg commented on src/components/common/InputBlock.jsx
> +    <InputBlockContainer draggable="true" onDragStart={onDragStart}>
말씀하신 것처럼, 현재 우리가 구현한 기능으로는 auto도 충분합니다!
true로 명시한 이유는 만약 InputBlockContainer의 요소가 drag가 불가능하도록 변경되더라도 프로젝트 기능 명세에 따르면 반드시 drag가 가능하도록 기능을 구현할 것이고, 명시적으로 true로 설정해놓으면 코드를 읽는 사람이 이해하기 쉽고 우리의 의도를 명확하게 파악할 수 있겠다고 판단했기 때문입니다!

2024-08-14 16:49 UTC, noeyigg commented on src/components/BlockDashboard.jsx
> +    <Section onDragOver={(e) => e.preventDefault()} onDrop={onDrop}>
좋은 지적 감사합니다! 제안해주신 방법을 사용하는 것이 더 깔끔하고 유지보수하기에도 용이하겠네요! 반영하겠습니다 :)

2024-08-14 16:55 UTC, noeyigg commented on src/components/common/LineBlock.jsx
> +    </LineBlockContainer>
switch문을 사용하면 블록의 타입에 따라 분기를 나누어 렌더링하는 로직을 더 한눈에 이해할 수 있겠네요! 
다만 블록의 타입이 없는 경우 default문이 실행되어 해당하는 div가 렌더링 될텐데, 이 요소가 화면에서 필요한 이유가 무엇이라고 생각하시는지 알 수 있을까요?

2024-08-14 20:28 UTC, whoisrey commented on src/components/common/LineBlock.jsx
> +    </LineBlockContainer>
> switch문을 사용하면 블록의 타입에 따라 분기를 나누어 렌더링하는 로직을 더 한눈에 이해할 수 있겠네요! 
> 
> 다만 블록의 타입이 없는 경우 default문이 실행되어 해당하는 div가 렌더링 될텐데, 이 요소가 화면에서 필요한 이유가 무엇이라고 생각하시는지 알 수 있을까요?

앗 제가 드렸던 예시가 기연님께 혼란을 드린 것 같습니다.
위에 div는 다른 타입의 블록이 들어왔을 때 그에 맞는 블록이 들어오는 가상 예시입니다! 우리 프로젝트와 맞게 바꾼다면 
```jsx
default
  return;
```
은 어떨까요~?

2024-08-15 01:44 UTC, noeyigg commented on src/pages/Main.jsx
> +  };
두 state를 하나로 관리하는 의견 아주 좋습니다!
그런데 아직 라인블록별로 블록이 생성되는 것이 아니라 dashboard에 있는 전체 블록이 state에 담기고 있습니다.
저는 현재 기능 구현이 충분히 되지 않은 상태니 협업을 위해서 다른 사람이 작성한 코드를 한 눈에 알아볼 수 있도록 작성하는 것이 중요하다고 생각합니다.
따라서 지금 state를 하나의 객체로 관리하기보다는 현 상태를 유지하고, 라인블록별로 블록을 생성하는 기능이 구현된 후에 리팩토링을 state를 하나로 관리하는 방향으로 진행하는 것은 어떨까요~?

2024-08-15 01:47 UTC, whoisrey commented on src/pages/Main.jsx
> +  };
좋습니다~!
저 역시 추후에 작업할 때 해당 사항이 변경되면 공유하겠습니다.

2024-08-15 01:49 UTC, noeyigg commented on src/components/common/LineBlock.jsx
> +    </LineBlockContainer>
네! 제가 작성한 if문에서는 말씀하신 경우에는 함수가 return되지 않겠네요! 타입의 분기를 나눌 때 코드가 조금 더 명확히 읽히는 것 같으니 반영하겠습니다 :)

그런데 현재 코드에서는 각각의 case에서 return으로 조건문을 종료하기에 괜찮지만, switch문은 모두 default문을 한번씩 실행한다는 특징이 있다는 점에서 if문을 사용하는 것보다 적절한지에 대해서는 고민이 되네요!

2024-08-15 01:52 UTC, whoisrey commented on src/components/common/LineBlock.jsx
> +    </LineBlockContainer>
맞아요~! 다른 type의 block을 대응하는 `return`문만 없다면 기연님이 작성하신 `if`문도 좋은 것 같습니다.

2024-08-15 02:28 UTC, whoisrey approved these changes
꼼꼼하게 수정하고 완료해주신 기연님! 
수고많으셨습니다.

2024-08-15 02:29 UTC, merged